title: backup-volume
description: Documentation for the enigmacurry/backup-volume Docker image.
theme: just-the-docs

url: https://enigmacurry.github.io/backup-volume/

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

aux_links:
  'GitHub Repository':
    - https://github.com/enigmacurry/backup-volume

nav_external_links:
  - title: GitHub Repository
    url: https://github.com/enigmacurry/backup-volume

footer_content: >-
  Copyright &copy; 2024 <a target="_blank" href="https://www.enigmacurry.software">enigmacurry.software</a> and contributors.
  Distributed under the <a href="https://github.com/enigmacurry/backup-volume/tree/main/LICENSE">MPL-2.0 License.</a><br>
  Something missing, unclear or not working? Open <a href="https://github.com/enigmacurry/backup-volume/issues">an issue</a>.
